import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "hi" | "te" | "ta" | "kn" | "bn" | "mr";

export const LANGUAGES = [
  { code: "en", label: "English", native: "English" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "te", label: "Telugu", native: "తెలుగు" },
  { code: "ta", label: "Tamil", native: "தமிழ்" },
  { code: "kn", label: "Kannada", native: "ಕನ್ನಡ" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
  { code: "mr", label: "Marathi", native: "मराठी" },
];

type TranslationMap = Record<string, string>;

const TRANSLATIONS: Record<Language, TranslationMap> = {
  en: {
    dashboard: "Dashboard",
    landmark_id: "Landmark ID",
    map_explorer: "Map Explorer",
    weather: "Weather",
    scout_ai: "Scout AI",
    budget: "Budget",
    travel_buddy: "Travel Buddy",
    hotel_bookings: "Hotel Bookings",
    my_profile: "My Profile",
    sign_out: "Sign Out",
    light_mode: "Light Mode",
    dark_mode: "Dark Mode",
    welcome_back: "Welcome back",
    start_exploring: "Start Exploring",
    ask_scout_ai: "Ask Scout AI",
    quick_actions: "Quick Actions",
    travel_wisdom: "Travel Wisdom",
    book_now: "Book Now",
    per_night: "per night",
    check_in: "Check-In",
    check_out: "Check-Out",
    guests: "Guests",
    total: "Total",
    continue_to_payment: "Continue to Payment",
    booking_confirmed: "Booking Confirmed!",
    done: "Done",
    plan_your_journey: "Plan Your Journey",
    recommended_stays: "Recommended Heritage Stays",
    find_route: "Find Route",
    route_planner: "Route Planner",
    nearby_explorer: "Nearby Explorer",
    send: "Send",
    new_chat: "New Chat",
    ask_scout: "Ask Scout AI...",
    heritage_stays: "Heritage Stays & Bookings",
    filters: "Filters",
    budget_filter: "Budget (per night)",
    search_location: "Search Location/Hotel",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    landmark_id: "स्मारक पहचान",
    map_explorer: "मानचित्र खोजकर्ता",
    weather: "मौसम",
    scout_ai: "स्काउट एआई",
    budget: "बजट",
    travel_buddy: "यात्रा साथी",
    hotel_bookings: "होटल बुकिंग",
    my_profile: "मेरी प्रोफ़ाइल",
    sign_out: "साइन आउट",
    light_mode: "लाइट मोड",
    dark_mode: "डार्क मोड",
    welcome_back: "वापस स्वागत है",
    start_exploring: "अन्वेषण शुरू करें",
    ask_scout_ai: "स्काउट एआई से पूछें",
    quick_actions: "त्वरित क्रियाएं",
    travel_wisdom: "यात्रा ज्ञान",
    book_now: "अभी बुक करें",
    per_night: "प्रति रात",
    check_in: "चेक-इन",
    check_out: "चेक-आउट",
    guests: "मेहमान",
    total: "कुल",
    continue_to_payment: "भुगतान जारी रखें",
    booking_confirmed: "बुकिंग की पुष्टि हो गई!",
    done: "हो गया",
    plan_your_journey: "अपनी यात्रा की योजना बनाएं",
    recommended_stays: "अनुशंसित विरासत ठहराव",
    find_route: "मार्ग खोजें",
    route_planner: "मार्ग योजनाकार",
    nearby_explorer: "आस-पास खोजकर्ता",
    send: "भेजें",
    new_chat: "नई चैट",
    ask_scout: "स्काउट एआई से पूछें...",
    heritage_stays: "विरासत ठहराव एवं बुकिंग",
    filters: "फ़िल्टर",
    budget_filter: "बजट (प्रति रात)",
    search_location: "स्थान/होटल खोजें",
  },
  te: {
    dashboard: "డాష్‌బోర్డ్",
    landmark_id: "ల్యాండ్‌మార్క్ గుర్తింపు",
    map_explorer: "మ్యాప్ ఎక్స్‌ప్లోరర్",
    weather: "వాతావరణం",
    scout_ai: "స్కౌట్ AI",
    budget: "బడ్జెట్",
    travel_buddy: "ప్రయాణ స్నేహితుడు",
    hotel_bookings: "హోటల్ బుకింగ్",
    my_profile: "నా ప్రొఫైల్",
    sign_out: "సైన్ అవుట్",
    light_mode: "లైట్ మోడ్",
    dark_mode: "డార్క్ మోడ్",
    welcome_back: "తిరిగి స్వాగతం",
    start_exploring: "అన్వేషణ ప్రారంభించండి",
    ask_scout_ai: "స్కౌట్ AI అడగండి",
    quick_actions: "త్వరిత చర్యలు",
    travel_wisdom: "ప్రయాణ జ్ఞానం",
    book_now: "ఇప్పుడే బుక్ చేయండి",
    per_night: "రాత్రికి",
    check_in: "చెక్-ఇన్",
    check_out: "చెక్-అవుట్",
    guests: "అతిథులు",
    total: "మొత్తం",
    continue_to_payment: "చెల్లింపుకు కొనసాగండి",
    booking_confirmed: "బుకింగ్ నిర్ధారించబడింది!",
    done: "పూర్తయింది",
    plan_your_journey: "మీ ప్రయాణాన్ని ప్లాన్ చేయండి",
    recommended_stays: "సిఫార్సు చేసిన వారసత్వ స్టేలు",
    find_route: "మార్గం కనుగొనండి",
    route_planner: "మార్గ ప్రణాళికదారు",
    nearby_explorer: "సమీప అన్వేషకుడు",
    send: "పంపండి",
    new_chat: "కొత్త చాట్",
    ask_scout: "స్కౌట్ AI అడగండి...",
    heritage_stays: "వారసత్వ స్టేలు & బుకింగ్స్",
    filters: "ఫిల్టర్లు",
    budget_filter: "బడ్జెట్ (రాత్రికి)",
    search_location: "స్థానం/హోటల్ శోధించండి",
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    landmark_id: "அடையாளம் காணல்",
    map_explorer: "வரைபட ஆய்வாளர்",
    weather: "வானிலை",
    scout_ai: "ஸ்கவுட் AI",
    budget: "பட்ஜெட்",
    travel_buddy: "பயண நண்பர்",
    hotel_bookings: "ஹோட்டல் முன்பதிவு",
    my_profile: "என் சுயவிவரம்",
    sign_out: "வெளியேறு",
    light_mode: "ஒளி பயன்முறை",
    dark_mode: "இருள் பயன்முறை",
    welcome_back: "மீண்டும் வரவேற்கிறோம்",
    start_exploring: "ஆய்வை தொடங்கு",
    ask_scout_ai: "ஸ்கவுட் AI-யிடம் கேளுங்கள்",
    quick_actions: "விரைவு செயல்கள்",
    travel_wisdom: "பயண ஞானம்",
    book_now: "இப்போதே முன்பதிவு செய்யவும்",
    per_night: "ஒரு இரவுக்கு",
    check_in: "செக்-இன்",
    check_out: "செக்-அவுட்",
    guests: "விருந்தினர்கள்",
    total: "மொத்தம்",
    continue_to_payment: "கட்டணத்திற்கு தொடரவும்",
    booking_confirmed: "முன்பதிவு உறுதிப்படுத்தப்பட்டது!",
    done: "முடிந்தது",
    plan_your_journey: "உங்கள் பயணத்தை திட்டமிடுங்கள்",
    recommended_stays: "பரிந்துரைக்கப்பட்ட பாரம்பரிய தங்குமிடங்கள்",
    find_route: "வழி கண்டுபிடி",
    route_planner: "வழித்தட திட்டமிடுபவர்",
    nearby_explorer: "அருகிலுள்ள ஆய்வாளர்",
    send: "அனுப்பு",
    new_chat: "புதிய அரட்டை",
    ask_scout: "ஸ்கவுட் AI-யிடம் கேளுங்கள்...",
    heritage_stays: "பாரம்பரிய தங்குமிடங்கள் & முன்பதிவுகள்",
    filters: "வடிப்பான்கள்",
    budget_filter: "பட்ஜெட் (ஒரு இரவுக்கு)",
    search_location: "இடம்/ஹோட்டலை தேடுங்கள்",
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    landmark_id: "ಲ್ಯಾಂಡ್‌ಮಾರ್ಕ್ ಗುರುತಿಸುವಿಕೆ",
    map_explorer: "ನಕ್ಷೆ ಅನ್ವೇಷಕ",
    weather: "ಹವಾಮಾನ",
    scout_ai: "ಸ್ಕೌಟ್ AI",
    budget: "ಬಜೆಟ್",
    travel_buddy: "ಪ್ರಯಾಣ ಸ್ನೇಹಿತ",
    hotel_bookings: "ಹೋಟೆಲ್ ಬುಕಿಂಗ್",
    my_profile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    sign_out: "ಸೈನ್ ಔಟ್",
    light_mode: "ಬೆಳಕಿನ ಮೋಡ್",
    dark_mode: "ಕತ್ತಲೆ ಮೋಡ್",
    welcome_back: "ಮತ್ತೆ ಸ್ವಾಗತ",
    start_exploring: "ಅನ್ವೇಷಿಸಿ ಪ್ರಾರಂಭಿಸಿ",
    ask_scout_ai: "ಸ್ಕೌಟ್ AI ಕೇಳಿ",
    quick_actions: "ತ್ವರಿತ ಕ್ರಮಗಳು",
    travel_wisdom: "ಪ್ರಯಾಣ ಜ್ಞಾನ",
    book_now: "ಈಗ ಬುಕ್ ಮಾಡಿ",
    per_night: "ರಾತ್ರಿಗೆ",
    check_in: "ಚೆಕ್-ಇನ್",
    check_out: "ಚೆಕ್-ಔಟ್",
    guests: "ಅತಿಥಿಗಳು",
    total: "ಒಟ್ಟು",
    continue_to_payment: "ಪಾವತಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    booking_confirmed: "ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    done: "ಮುಗಿದಿದೆ",
    plan_your_journey: "ನಿಮ್ಮ ಪ್ರಯಾಣ ಯೋಜಿಸಿ",
    recommended_stays: "ಶಿಫಾರಸು ಮಾಡಿದ ಪಾರಂಪರಿಕ ತಂಗುದಾಣ",
    find_route: "ಮಾರ್ಗ ಹುಡುಕಿ",
    route_planner: "ಮಾರ್ಗ ಯೋಜಕ",
    nearby_explorer: "ಹತ್ತಿರದ ಅನ್ವೇಷಕ",
    send: "ಕಳುಹಿಸಿ",
    new_chat: "ಹೊಸ ಚಾಟ್",
    ask_scout: "ಸ್ಕೌಟ್ AI ಕೇಳಿ...",
    heritage_stays: "ಪಾರಂಪರಿಕ ತಂಗುದಾಣ & ಬುಕಿಂಗ್ಸ್",
    filters: "ಫಿಲ್ಟರ್‌ಗಳು",
    budget_filter: "ಬಜೆಟ್ (ರಾತ್ರಿಗೆ)",
    search_location: "ಸ್ಥಳ/ಹೋಟೆಲ್ ಹುಡುಕಿ",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    landmark_id: "ল্যান্ডমার্ক শনাক্তকরণ",
    map_explorer: "মানচিত্র অন্বেষক",
    weather: "আবহাওয়া",
    scout_ai: "স্কাউট AI",
    budget: "বাজেট",
    travel_buddy: "ভ্রমণ বন্ধু",
    hotel_bookings: "হোটেল বুকিং",
    my_profile: "আমার প্রোফাইল",
    sign_out: "সাইন আউট",
    light_mode: "লাইট মোড",
    dark_mode: "ডার্ক মোড",
    welcome_back: "আবার স্বাগতম",
    start_exploring: "অন্বেষণ শুরু করুন",
    ask_scout_ai: "স্কাউট AI-এ জিজ্ঞেস করুন",
    quick_actions: "দ্রুত ক্রিয়া",
    travel_wisdom: "ভ্রমণ জ্ঞান",
    book_now: "এখনই বুক করুন",
    per_night: "প্রতি রাতে",
    check_in: "চেক-ইন",
    check_out: "চেক-আউট",
    guests: "অতিথিরা",
    total: "মোট",
    continue_to_payment: "পেমেন্টে চালিয়ে যান",
    booking_confirmed: "বুকিং নিশ্চিত হয়েছে!",
    done: "সম্পন্ন",
    plan_your_journey: "আপনার যাত্রা পরিকল্পনা করুন",
    recommended_stays: "প্রস্তাবিত ঐতিহ্য আবাসন",
    find_route: "পথ খুঁজুন",
    route_planner: "পথ পরিকল্পনাকারী",
    nearby_explorer: "কাছাকাছি অন্বেষক",
    send: "পাঠান",
    new_chat: "নতুন চ্যাট",
    ask_scout: "স্কাউট AI-এ জিজ্ঞেস করুন...",
    heritage_stays: "ঐতিহ্য আবাসন ও বুকিং",
    filters: "ফিল্টার",
    budget_filter: "বাজেট (প্রতি রাতে)",
    search_location: "অবস্থান/হোটেল অনুসন্ধান করুন",
  },
  mr: {
    dashboard: "डॅशबोर्ड",
    landmark_id: "खूण ओळख",
    map_explorer: "नकाशा अन्वेषक",
    weather: "हवामान",
    scout_ai: "स्काउट AI",
    budget: "अर्थसंकल्प",
    travel_buddy: "प्रवास मित्र",
    hotel_bookings: "हॉटेल बुकिंग",
    my_profile: "माझी प्रोफाइल",
    sign_out: "साइन आउट",
    light_mode: "प्रकाश मोड",
    dark_mode: "गडद मोड",
    welcome_back: "परत स्वागत आहे",
    start_exploring: "शोध सुरू करा",
    ask_scout_ai: "स्काउट AI ला विचारा",
    quick_actions: "जलद क्रिया",
    travel_wisdom: "प्रवास ज्ञान",
    book_now: "आत्ता बुक करा",
    per_night: "प्रति रात्र",
    check_in: "चेक-इन",
    check_out: "चेक-आउट",
    guests: "पाहुणे",
    total: "एकूण",
    continue_to_payment: "देयकाकडे सुरू ठेवा",
    booking_confirmed: "बुकिंग पुष्टी झाली!",
    done: "झाले",
    plan_your_journey: "आपला प्रवास नियोजित करा",
    recommended_stays: "शिफारस केलेले वारसा निवास",
    find_route: "मार्ग शोधा",
    route_planner: "मार्ग नियोजक",
    nearby_explorer: "जवळचा अन्वेषक",
    send: "पाठवा",
    new_chat: "नवीन चॅट",
    ask_scout: "स्काउट AI ला विचारा...",
    heritage_stays: "वारसा निवास आणि बुकिंग",
    filters: "फिल्टर",
    budget_filter: "अर्थसंकल्प (प्रति रात्र)",
    search_location: "स्थान/हॉटेल शोधा",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(
    () => (localStorage.getItem("yatra_lang") as Language) || "en"
  );

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("yatra_lang", lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language][key] || TRANSLATIONS["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;
